name: ML Pipeline CI/CD

# Déclencheurs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * 1"  # chaque lundi à 2h du matin
  workflow_dispatch:

jobs:
  build-train:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      #  Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #  Ajouter src au PYTHONPATH pour les imports
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      #  Créer les dossiers data et model si inexistants
      - name: Ensure data and model folders exist
        run: |
          mkdir -p data
          mkdir -p model

      # Lancer les tests
      - name: Run tests
        run: 
            export PYTHONPATH=${{ github.workspace }}/src
            tests/

      # Mettre à jour le dataset et entraîner le modèle
      - name: Update dataset and train model
        run: |
          python src/update_data.py
          python src/train_model.py

      # Commit et push dataset + modèle
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/cleaned_dataset.csv model/model.pkl
          git commit -m "Update dataset and model [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
